spring:
  profiles:
    active: @spring.profiles.active@
  application:
    name: maengelDB
  datasource:
    url: jdbc:${profile.datasource.url}
    username: ${profile.datasource.user}
    password: ${profile.datasource.pass}
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: false
        jdbc:
          time_zone: UTC
    hibernate:
      ddl-auto: update

server:
  servlet:
    context-path: "/api"
  error:
    include-message: always

security:
  jwt:
    secret: "super-secret"
    expiresAfterMinutes: 30