profile:
  datasource:
    url: ${DATABASE_JDBC}
    user: ${DATABASE_USER}
    pass: ${DATABASE_PASS}
    type: org.apache.tomcat.jdbc.pool.DataSource

  database:
    platform: org.hibernate.dialect.PostgreSQLDialect